services:
  database:
    image: "postgres:latest"
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
  database-test:
    image: "postgres:latest"
    ports:
      - ${DB_TEST_PORT}:${DB_TEST_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_TEST_NAME}
    volumes:
      - ./pgdatatest/:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - database
  pgadmin-test:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4-test
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5051:80'
    depends_on:
      - database-test